name: Run Build

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: "Name of the app to build"
        required: true
        default: "Untitled App"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Dummy Upload Token (upload will fail if empty)
      UPLOAD_TOKEN: "1234567890abcdef"
    defaults:
      run:
        working-directory: ./cli

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # CLI call to make sure the build and upload scripts are executable
      - name: Make scripts executable
        run: |
          chmod +x build.sh
          chmod +x upload.sh
          echo "Scripts are now executable."

      # CLI call to simulated build process
      - name: Run Build
        run: |
          ./build.sh --platform Android --project-name "${{ github.event.inputs.app_name }}"
          echo "Build process completed."

      # CLI call to simulated upload process
      # Modify later with an if statement to adjust flags based on platform
      - name: Upload
        run: |
          for file in ./build/Android/*; do
            echo "Uploading file: $file"
            ./upload.sh android "$file"
          done
          echo "Upload process completed for all artifacts."
